/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import modelo.VeiculoVO;
import servicos.ServicosFactory;
import servicos.VeiculoServicos;

/**
 * @author André Luiz Alves
 * @since 10/07/2018 - 16h34
 * @version 1.0 meta charset
 */
public class GUIAlteraVeiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIAlteraVeiculo
     */
    public GUIAlteraVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFuel = new javax.swing.ButtonGroup();
        bgPortas = new javax.swing.ButtonGroup();
        jlpAlterar = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlMarca = new javax.swing.JLabel();
        jlAno = new javax.swing.JLabel();
        jlModelo = new javax.swing.JLabel();
        jlCombustivel = new javax.swing.JLabel();
        jlValor = new javax.swing.JLabel();
        jlCor = new javax.swing.JLabel();
        jlPortas = new javax.swing.JLabel();
        jlComplementos = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtMarca = new javax.swing.JTextField();
        jtAno = new javax.swing.JTextField();
        jtModelo = new javax.swing.JTextField();
        jtValor = new javax.swing.JTextField();
        jtCor = new javax.swing.JTextField();
        jrbGasolina = new javax.swing.JRadioButton();
        jrbGnv = new javax.swing.JRadioButton();
        jrbEtanol = new javax.swing.JRadioButton();
        jrbDiesel = new javax.swing.JRadioButton();
        jrbFlex = new javax.swing.JRadioButton();
        jrb2p = new javax.swing.JRadioButton();
        jrb3p = new javax.swing.JRadioButton();
        jrb4p = new javax.swing.JRadioButton();
        jlCodigo = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jcAr = new javax.swing.JCheckBox();
        jcAirBag = new javax.swing.JCheckBox();
        jcDirecao = new javax.swing.JCheckBox();
        jbConfirmar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Alterar Dados do Veículo");

        jlpAlterar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome:");

        jlMarca.setText("Marca:");

        jlAno.setText("Ano:");

        jlModelo.setText("Modelo:");

        jlCombustivel.setText("Combustível:");

        jlValor.setText("Valor de Custo:");

        jlCor.setText("Cor:");

        jlPortas.setText("Portas:");

        jlComplementos.setText("Complementos:");

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jtMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtMarcaFocusLost(evt);
            }
        });
        jtMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtMarcaKeyPressed(evt);
            }
        });

        jtAno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtAnoFocusLost(evt);
            }
        });
        jtAno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtAnoKeyPressed(evt);
            }
        });

        jtModelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtModeloFocusLost(evt);
            }
        });
        jtModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtModeloKeyPressed(evt);
            }
        });

        jtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtValorFocusLost(evt);
            }
        });
        jtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtValorKeyPressed(evt);
            }
        });

        jtCor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCorFocusLost(evt);
            }
        });
        jtCor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCorKeyPressed(evt);
            }
        });

        bgFuel.add(jrbGasolina);
        jrbGasolina.setText("Gasolina");
        jrbGasolina.setActionCommand("Gasolina");
        jrbGasolina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbGasolinaKeyPressed(evt);
            }
        });

        bgFuel.add(jrbGnv);
        jrbGnv.setText("GNV");
        jrbGnv.setActionCommand("Gnv");
        jrbGnv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbGnvKeyPressed(evt);
            }
        });

        bgFuel.add(jrbEtanol);
        jrbEtanol.setText("Etanol");
        jrbEtanol.setActionCommand("Etanol");
        jrbEtanol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbEtanolKeyPressed(evt);
            }
        });

        bgFuel.add(jrbDiesel);
        jrbDiesel.setText("Diesel");
        jrbDiesel.setActionCommand("Diesel");
        jrbDiesel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbDieselKeyPressed(evt);
            }
        });

        bgFuel.add(jrbFlex);
        jrbFlex.setText("Flex");
        jrbFlex.setActionCommand("Flex");
        jrbFlex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbFlexKeyPressed(evt);
            }
        });

        bgPortas.add(jrb2p);
        jrb2p.setText("2");
        jrb2p.setActionCommand("2");
        jrb2p.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrb2pKeyPressed(evt);
            }
        });

        bgPortas.add(jrb3p);
        jrb3p.setText("3");
        jrb3p.setActionCommand("3");
        jrb3p.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrb3pKeyPressed(evt);
            }
        });

        bgPortas.add(jrb4p);
        jrb4p.setText("4");
        jrb4p.setActionCommand("4");
        jrb4p.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrb4pKeyPressed(evt);
            }
        });

        jlCodigo.setText("Código:");

        jtCodigo.setEnabled(false);

        jcAr.setText("Ar Condicionado");
        jcAr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcArKeyPressed(evt);
            }
        });

        jcAirBag.setText("AirBag");
        jcAirBag.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcAirBagKeyPressed(evt);
            }
        });

        jcDirecao.setText("Direção Hidráulica");
        jcDirecao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcDirecaoKeyPressed(evt);
            }
        });

        jbConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        jbConfirmar.setText("Confirmar Alteração");
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });
        jbConfirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbConfirmarKeyPressed(evt);
            }
        });

        jlpAlterar.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlAno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlModelo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlCombustivel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlValor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlCor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlPortas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlComplementos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtAno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtModelo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtValor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtCor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jrbGasolina, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jrbGnv, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jrbEtanol, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jrbDiesel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jrbFlex, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jrb2p, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jrb3p, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jrb4p, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jcAr, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jcAirBag, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jcDirecao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jbConfirmar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAlterarLayout = new javax.swing.GroupLayout(jlpAlterar);
        jlpAlterar.setLayout(jlpAlterarLayout);
        jlpAlterarLayout.setHorizontalGroup(
            jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpAlterarLayout.createSequentialGroup()
                        .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jlpAlterarLayout.createSequentialGroup()
                                .addComponent(jlCodigo)
                                .addGap(18, 18, 18)
                                .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jlpAlterarLayout.createSequentialGroup()
                                .addComponent(jlModelo)
                                .addGap(18, 18, 18)
                                .addComponent(jtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNome)
                            .addComponent(jlCor))
                        .addGap(18, 18, 18)
                        .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jtCor))
                        .addGap(18, 18, 18)
                        .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlValor)
                            .addComponent(jlMarca))
                        .addGap(18, 18, 18)
                        .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpAlterarLayout.createSequentialGroup()
                                .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlPortas)
                                .addGap(21, 21, 21)
                                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jlpAlterarLayout.createSequentialGroup()
                                        .addComponent(jrb2p)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrb3p))
                                    .addComponent(jrb4p)))
                            .addGroup(jlpAlterarLayout.createSequentialGroup()
                                .addComponent(jtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jlAno)
                                .addGap(18, 18, 18)
                                .addComponent(jtAno))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpAlterarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbConfirmar))
                    .addGroup(jlpAlterarLayout.createSequentialGroup()
                        .addComponent(jlCombustivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbGasolina)
                            .addComponent(jrbEtanol))
                        .addGap(18, 18, 18)
                        .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbDiesel)
                            .addGroup(jlpAlterarLayout.createSequentialGroup()
                                .addComponent(jrbGnv)
                                .addGap(18, 18, 18)
                                .addComponent(jrbFlex)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(jlComplementos)))
                        .addGap(18, 18, 18)
                        .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcAirBag)
                            .addGroup(jlpAlterarLayout.createSequentialGroup()
                                .addComponent(jcAr)
                                .addGap(18, 18, 18)
                                .addComponent(jcDirecao)))))
                .addContainerGap())
        );
        jlpAlterarLayout.setVerticalGroup(
            jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAlterarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigo)
                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMarca)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAno)
                    .addComponent(jtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCor)
                    .addComponent(jtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlValor)
                    .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPortas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrb2p)
                    .addComponent(jrb3p)
                    .addComponent(jlModelo)
                    .addComponent(jtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb4p)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpAlterarLayout.createSequentialGroup()
                        .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCombustivel)
                            .addComponent(jrbGasolina)
                            .addComponent(jrbGnv)
                            .addComponent(jrbFlex))
                        .addGap(4, 4, 4)
                        .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbEtanol)
                            .addComponent(jrbDiesel)))
                    .addGroup(jlpAlterarLayout.createSequentialGroup()
                        .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcAr)
                            .addComponent(jlComplementos)
                            .addComponent(jcDirecao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcAirBag)))
                .addGap(18, 18, 18)
                .addComponent(jbConfirmar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpAlterar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarAlteracao() {

        try {
            VeiculoVO objVeiculoVO = new VeiculoVO();
            objVeiculoVO.setIdVeiculo(Long.parseLong(jtCodigo.getText()));

            if (!jtNome.getText().isEmpty()) {
                objVeiculoVO.setNome(jtNome.getText());
            } else {
                throw new NumberFormatException("Nome Inválido!");
            }
            if (!jtMarca.getText().isEmpty()) {
                objVeiculoVO.setMarca(jtMarca.getText());
            } else {
                throw new NumberFormatException("Marca Inválida!");
            }
            if (!jtAno.getText().isEmpty()) {
                objVeiculoVO.setAno(Integer.parseInt(jtAno.getText()));
            } else {
                throw new NumberFormatException("Ano Inválido!");
            }
            if (!jtModelo.getText().isEmpty()) {
                objVeiculoVO.setModelo(Integer.parseInt(jtModelo.getText()));
            } else {
                throw new NumberFormatException("Modelo Inválido!");
            }
            if (!jtValor.getText().isEmpty()) {
                objVeiculoVO.setValorCusto(Double.parseDouble(jtValor.getText()));
            } else {
                throw new NumberFormatException("Valor Inválido!");
            }
            if (!jtCor.getText().isEmpty()) {
                objVeiculoVO.setCor(jtCor.getText());
            } else {
                throw new NumberFormatException("Cor Inválida!");
            }
            if (bgFuel.getSelection() != null) {
                objVeiculoVO.setCombustivel(bgFuel.getSelection().getActionCommand());
            } else {
                throw new NumberFormatException("Informe o Combustível!");
            }
            if (bgPortas.getSelection() != null) {
                objVeiculoVO.setPortas(bgPortas.getSelection().getActionCommand());
            } else {
                throw new NumberFormatException("Quantas Portas Tem?!");
            }

            ArrayList<String> complementos = new ArrayList<>();

            if (jcAr.isSelected()) {
                complementos.add("Sim");
            } else {
                complementos.add("Não");
            }
            if (jcDirecao.isSelected()) {
                complementos.add("Sim");
            } else {
                complementos.add("Não");
            }
            if (jcAirBag.isSelected()) {
                complementos.add("Sim");
            } else {
                complementos.add("Não");
            }

            objVeiculoVO.setComplementos(complementos);

            VeiculoServicos VS = ServicosFactory.getVeiculosServicos();
            VS.alterarVeiculo(objVeiculoVO);
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Alteração efetuada com sucesso!",
                    "Sistema",
                    JOptionPane.PLAIN_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Algum erro aconteceu!" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpar() {
        jtCodigo.setText(null);
        jtNome.setText(null);
        jtMarca.setText(null);
        jtAno.setText(null);
        jtModelo.setText(null);
        jtValor.setText(null);
        jtCor.setText(null);
        bgFuel.clearSelection();
        bgPortas.clearSelection();
        jcAr.setSelected(false);
        jcDirecao.setSelected(false);
        jcAirBag.setSelected(false);
    }
    
    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        if (jtNome.getText().isEmpty()) {
            jtNome.setBackground(Color.decode("#FFFFF0"));
            jtNome.setBorder(BorderFactory.createLineBorder(Color.red));
        } else {
            jtNome.setBackground(Color.white);
            jtNome.setBorder(BorderFactory.createLineBorder(Color.gray));
        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtMarca.grabFocus();
        }
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jtMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtMarcaFocusLost
        if (jtMarca.getText().isEmpty()) {
            jtMarca.setBackground(Color.decode("#FFFFF0"));
            jtMarca.setBorder(BorderFactory.createLineBorder(Color.red));
        } else {
            jtMarca.setBackground(Color.white);
            jtMarca.setBorder(BorderFactory.createLineBorder(Color.gray));
        }
    }//GEN-LAST:event_jtMarcaFocusLost

    private void jtMarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtMarcaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtAno.grabFocus();
        }
    }//GEN-LAST:event_jtMarcaKeyPressed

    private void jtAnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAnoFocusLost
        if (jtAno.getText().isEmpty()) {
            jtAno.setBackground(Color.decode("#FFFFF0"));
            jtAno.setBorder(BorderFactory.createLineBorder(Color.red));
        } else {
            jtAno.setBackground(Color.white);
            jtAno.setBorder(BorderFactory.createLineBorder(Color.gray));
        }
    }//GEN-LAST:event_jtAnoFocusLost

    private void jtAnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtAnoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtModelo.grabFocus();
        }
    }//GEN-LAST:event_jtAnoKeyPressed

    private void jtModeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtModeloFocusLost
        if (jtModelo.getText().isEmpty()) {
            jtModelo.setBackground(Color.decode("#FFFFF0"));
            jtModelo.setBorder(BorderFactory.createLineBorder(Color.red));
        } else {
            jtModelo.setBackground(Color.white);
            jtModelo.setBorder(BorderFactory.createLineBorder(Color.gray));
        }
    }//GEN-LAST:event_jtModeloFocusLost

    private void jtModeloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtModeloKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtCor.grabFocus();
        }
    }//GEN-LAST:event_jtModeloKeyPressed

    private void jtValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtValorFocusLost
        if (jtValor.getText().isEmpty()) {
            jtValor.setBackground(Color.decode("#FFFFF0"));
            jtValor.setBorder(BorderFactory.createLineBorder(Color.red));
        } else {
            jtValor.setBackground(Color.white);
            jtValor.setBorder(BorderFactory.createLineBorder(Color.gray));
        }
    }//GEN-LAST:event_jtValorFocusLost

    private void jtValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtValorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrbGasolina.grabFocus();
        }
    }//GEN-LAST:event_jtValorKeyPressed

    private void jtCorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCorFocusLost
        if (jtCor.getText().isEmpty()) {
            jtCor.setBackground(Color.decode("#FFFFF0"));
            jtCor.setBorder(BorderFactory.createLineBorder(Color.red));
        } else {
            jtCor.setBackground(Color.white);
            jtCor.setBorder(BorderFactory.createLineBorder(Color.gray));
        }
    }//GEN-LAST:event_jtCorFocusLost

    private void jtCorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtValor.grabFocus();
        }
    }//GEN-LAST:event_jtCorKeyPressed

    private void jrbGasolinaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbGasolinaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrbGnv.grabFocus();
        }
    }//GEN-LAST:event_jrbGasolinaKeyPressed

    private void jrbGnvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbGnvKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrbFlex.grabFocus();
        }
    }//GEN-LAST:event_jrbGnvKeyPressed

    private void jrbEtanolKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbEtanolKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrbDiesel.grabFocus();
        }
    }//GEN-LAST:event_jrbEtanolKeyPressed

    private void jrbDieselKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbDieselKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrb2p.grabFocus();
        }
    }//GEN-LAST:event_jrbDieselKeyPressed

    private void jrbFlexKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbFlexKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrbEtanol.grabFocus();
        }
    }//GEN-LAST:event_jrbFlexKeyPressed

    private void jrb2pKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrb2pKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrb3p.grabFocus();
        }
    }//GEN-LAST:event_jrb2pKeyPressed

    private void jrb3pKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrb3pKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrb4p.grabFocus();
        }
    }//GEN-LAST:event_jrb3pKeyPressed

    private void jrb4pKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrb4pKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcAr.grabFocus();
        }
    }//GEN-LAST:event_jrb4pKeyPressed

    private void jcArKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcArKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcDirecao.grabFocus();
        }
    }//GEN-LAST:event_jcArKeyPressed

    private void jcAirBagKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcAirBagKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmarAlteracao();
            limpar();
            dispose();
        }
    }//GEN-LAST:event_jcAirBagKeyPressed

    private void jcDirecaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcDirecaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcAirBag.grabFocus();
        }
    }//GEN-LAST:event_jcDirecaoKeyPressed

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        confirmarAlteracao();
        limpar();
        dispose();

    }//GEN-LAST:event_jbConfirmarActionPerformed

    private void jbConfirmarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbConfirmarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmarAlteracao();
            limpar();
            dispose();
        }
    }//GEN-LAST:event_jbConfirmarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFuel;
    private javax.swing.ButtonGroup bgPortas;
    private javax.swing.JButton jbConfirmar;
    public static javax.swing.JCheckBox jcAirBag;
    public static javax.swing.JCheckBox jcAr;
    public static javax.swing.JCheckBox jcDirecao;
    private javax.swing.JLabel jlAno;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlCombustivel;
    private javax.swing.JLabel jlComplementos;
    private javax.swing.JLabel jlCor;
    private javax.swing.JLabel jlMarca;
    private javax.swing.JLabel jlModelo;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlPortas;
    private javax.swing.JLabel jlValor;
    private javax.swing.JLayeredPane jlpAlterar;
    public static javax.swing.JRadioButton jrb2p;
    public static javax.swing.JRadioButton jrb3p;
    public static javax.swing.JRadioButton jrb4p;
    public static javax.swing.JRadioButton jrbDiesel;
    public static javax.swing.JRadioButton jrbEtanol;
    public static javax.swing.JRadioButton jrbFlex;
    public static javax.swing.JRadioButton jrbGasolina;
    public static javax.swing.JRadioButton jrbGnv;
    public static javax.swing.JTextField jtAno;
    public static javax.swing.JTextField jtCodigo;
    public static javax.swing.JTextField jtCor;
    public static javax.swing.JTextField jtMarca;
    public static javax.swing.JTextField jtModelo;
    public static javax.swing.JTextField jtNome;
    public static javax.swing.JTextField jtValor;
    // End of variables declaration//GEN-END:variables
}
