/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ClienteVO;
import servicos.ClienteServicos;
import servicos.ServicosFactory;

/**
 *
 * @author André Luiz & Eduardo Gautier
 * @since 07/07/2018 - 09h53
 * @version 1.0 meta charset
 */
public class GUIBuscaCliente extends javax.swing.JInternalFrame {

    private final DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{
                "Código",
                "Nome",
                "CPF",
                "Sexo",
                "Idade",
                "Rua", "Nº",
                "Bairro",
                "Cidade",
                "Estado"
            }
    );

    /**
     * Creates new form GUIBuscaCliente
     */
    public GUIBuscaCliente() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        jlpDados = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableCliente = new javax.swing.JTable();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbAtualizar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jlpFiltro = new javax.swing.JLayeredPane();
        jlFiltrar = new javax.swing.JLabel();
        jcomboFiltrar = new javax.swing.JComboBox<>();
        jtFiltrar = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Clientes");
        setMinimumSize(new java.awt.Dimension(800, 455));
        setPreferredSize(new java.awt.Dimension(800, 455));

        jlpDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtableCliente.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtableCliente);

        jlpDados.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );

        jlpAcoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atualizar.png"))); // NOI18N
        jbAtualizar.setText("Atualizar");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });
        jbAtualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbAtualizarKeyPressed(evt);
            }
        });

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jbDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/erro.png"))); // NOI18N
        jbDeletar.setText("Deletar");
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });
        jbDeletar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbDeletarKeyPressed(evt);
            }
        });

        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.setPreferredSize(new java.awt.Dimension(103, 41));
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });
        jbAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbAlterarKeyPressed(evt);
            }
        });

        jlpAcoes.setLayer(jbAtualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbDeletar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpAcoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );

        jlpFiltro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlFiltrar.setText("Filtrar:");

        jcomboFiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome", "CPF", "Sexo", "Idade", "Rua", "Nº", "Bairro", "Cidade", "Estado" }));
        jcomboFiltrar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcomboFiltrarItemStateChanged(evt);
            }
        });

        jtFiltrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtFiltrarKeyReleased(evt);
            }
        });

        jlpFiltro.setLayer(jlFiltrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpFiltro.setLayer(jcomboFiltrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpFiltro.setLayer(jtFiltrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpFiltroLayout = new javax.swing.GroupLayout(jlpFiltro);
        jlpFiltro.setLayout(jlpFiltroLayout);
        jlpFiltroLayout.setHorizontalGroup(
            jlpFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpFiltroLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jlFiltrar)
                .addGap(18, 18, 18)
                .addComponent(jtFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jcomboFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jlpFiltroLayout.setVerticalGroup(
            jlpFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jlpFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcomboFiltrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpDados)
                    .addComponent(jlpAcoes)
                    .addComponent(jlpFiltro))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpDados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void preencherTabela() {
        try {
            ClienteServicos cs = ServicosFactory.getClienteServicos();
            ArrayList<ClienteVO> clientes = cs.buscarCliente();

            for (int i = 0; i < clientes.size(); i++) {
                dtm.addRow(new String[]{
                    String.valueOf(clientes.get(i).getIdCliente()),
                    clientes.get(i).getNome(),
                    String.valueOf(clientes.get(i).getCpf()),
                    clientes.get(i).getSexo(),
                    String.valueOf(clientes.get(i).getIdade()),
                    clientes.get(i).getEndereco().getRua(),
                    String.valueOf(clientes.get(i).getEndereco().getNumero()),
                    clientes.get(i).getEndereco().getBairro(),
                    clientes.get(i).getEndereco().getCidade(),
                    clientes.get(i).getEndereco().getEstado()
                });
            }
            jtableCliente.setModel(dtm);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! " + e.getMessage(),
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    public void limparTabela() {
        dtm.setNumRows(0);
    }

    private void deletar() {
        try {
            int linha = jtableCliente.getSelectedRow();

            if (linha == -1) {
                JOptionPane.showMessageDialog(rootPane, "Você não selecionou nenhuma linha!");
            } else {
                ClienteServicos cs = ServicosFactory.getClienteServicos();
                String idCliente = (String) jtableCliente.getValueAt(linha, 0);
                cs.deletarCliente(Long.parseLong(idCliente));

                JOptionPane.showMessageDialog(
                        rootPane,
                        "Cliente Excluído com Sucesso!",
                        "Sistema",
                        JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro ao deletar! " + e.getMessage(),
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void filtrarClientes() {
        try {
            if (jtFiltrar.getText().isEmpty()) {
                limparTabela();
                preencherTabela();
            } else {
                String filtro = (String) jcomboFiltrar.getSelectedItem();
                String query = "";

                switch (filtro) {
                    case "Código":
                        query = "where c.idcliente = " + jtFiltrar.getText();
                        break;
                    case "Nome":
                        query = "where c.nome like '%" + jtFiltrar.getText() + "%'";
                        break;
                    case "CPF":
                        query = "where c.cpf like '%" + jtFiltrar.getText() + "%'";
                        break;
                    case "Sexo":
                        query = "where c.sexo like '%" + jtFiltrar.getText() + "%'";
                        break;
                    case "Idade":
                        query = "where c.idade = " + jtFiltrar.getText();
                        break;
                    case "Rua":
                        query = "where e.rua like '%" + jtFiltrar.getText() + "%'";
                        break;
                    case "Nº":
                        query = "where e.numero = " + jtFiltrar.getText();
                        break;
                    case "Bairro":
                        query = "where e.bairro like '%" + jtFiltrar.getText() + "%'";
                        break;
                    case "Cidade":
                        query = "where e.cidade like '%" + jtFiltrar.getText() + "%'";
                        break;
                    case "Estado":
                        query = "where e.estado like '%" + jtFiltrar.getText() + "%'";
                        break;
                    default:
                        break;
                }

                ClienteServicos cs = ServicosFactory.getClienteServicos();
                ArrayList<ClienteVO> clientes = cs.filtrar(query);

                for (int i = 0; i < clientes.size(); i++) {
                    dtm.addRow(new String[]{
                        String.valueOf(clientes.get(i).getIdCliente()),
                        clientes.get(i).getNome(),
                        String.valueOf(clientes.get(i).getCpf()),
                        clientes.get(i).getSexo(),
                        String.valueOf(clientes.get(i).getIdade()),
                        clientes.get(i).getEndereco().getRua(),
                        String.valueOf(clientes.get(i).getEndereco().getNumero()),
                        clientes.get(i).getEndereco().getBairro(),
                        clientes.get(i).getEndereco().getCidade(),
                        clientes.get(i).getEndereco().getEstado()
                    });
                }//fecha for
                jtableCliente.setModel(dtm);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! " + e.getMessage(),
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void alterar() {
        int linha = jtableCliente.getSelectedRow();
        if (linha != -1) {
            GUIAlteraCliente.jtCodigo.setText((String) jtableCliente.getValueAt(linha, 0));
            GUIAlteraCliente.jtNome.setText((String) jtableCliente.getValueAt(linha, 1));
            GUIAlteraCliente.jtCpf.setText((String) jtableCliente.getValueAt(linha, 2));

            //15:23
            String sexo = jtableCliente.getValueAt(linha, 3).toString();

            if (sexo.equalsIgnoreCase("Masculino")) {
                GUIAlteraCliente.jrbMasculino.setSelected(true);
            } else if (sexo.equalsIgnoreCase("Feminino")) {
                GUIAlteraCliente.jrbFeminino.setSelected(true);
            } else {
                GUIAlteraCliente.jrbOutros.setSelected(true);
            }

            GUIAlteraCliente.jtIdade.setText((String) jtableCliente.getValueAt(linha, 4));
            GUIAlteraCliente.jtRua.setText((String) jtableCliente.getValueAt(linha, 5));
            GUIAlteraCliente.jtN.setText((String) jtableCliente.getValueAt(linha, 6));
            GUIAlteraCliente.jtBairro.setText((String) jtableCliente.getValueAt(linha, 7));
            GUIAlteraCliente.jtCidade.setText((String) jtableCliente.getValueAt(linha, 8));
            GUIAlteraCliente.jtEstado.setText((String) jtableCliente.getValueAt(linha, 9));
        } else {
            JOptionPane.showMessageDialog(this,
                    "Você não selecionou nenhuma linha!");
        }
    }

    private void abrirAlterar() {
        GUIAlteraCliente objGUI = new GUIAlteraCliente();
        Menu.jAreaDeTrabalho.add(objGUI);
        objGUI.setVisible(true);
    }

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limparTabela();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbAtualizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbAtualizarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limparTabela();
            preencherTabela();
        }
    }//GEN-LAST:event_jbAtualizarKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limparTabela();
        }
    }//GEN-LAST:event_jbLimparKeyPressed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        int op = JOptionPane.showConfirmDialog(
                null,
                "Deseja Realmente Excluir?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (op == 0) {
            deletar();
            limparTabela();
            preencherTabela();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "Cancelado com Sucesso!",
                    "Sistema",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jbDeletarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbDeletarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int op = JOptionPane.showConfirmDialog(
                    null,
                    "Deseja Realmente Excluir?",
                    "Confirmação",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (op == 0) {
                deletar();
                limparTabela();
                preencherTabela();
            } else {
                JOptionPane.showMessageDialog(
                        null,
                        "Cancelado com Sucesso!",
                        "Sistema",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbDeletarKeyPressed

    private void jcomboFiltrarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcomboFiltrarItemStateChanged
        limparTabela();
        filtrarClientes();
    }//GEN-LAST:event_jcomboFiltrarItemStateChanged

    private void jtFiltrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtFiltrarKeyReleased
        limparTabela();
        filtrarClientes();
    }//GEN-LAST:event_jtFiltrarKeyReleased

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        abrirAlterar();
        alterar();
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbAlterarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            abrirAlterar();
            alterar();
        }
    }//GEN-LAST:event_jbAlterarKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JComboBox<String> jcomboFiltrar;
    private javax.swing.JLabel jlFiltrar;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JLayeredPane jlpFiltro;
    private javax.swing.JTextField jtFiltrar;
    public javax.swing.JTable jtableCliente;
    // End of variables declaration//GEN-END:variables
}
