/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import modelo.UsuarioVO;
import servicos.ServicosFactory;
import servicos.UsuarioServicos;

/**
 *
 * @author André Luiz Alves & Eduardo Gautier
 * @since 06/07/2018 - 18h45
 * @version 1.0 meta charset
 */
public class GUILogin extends javax.swing.JFrame {

    private int cont = 0;

    /**
     * Creates new form GUILogin
     */
    public GUILogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlpLogin = new javax.swing.JLayeredPane();
        jlLogin = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jbLogar = new javax.swing.JButton();
        jlIcone = new javax.swing.JLabel();
        jtLogin = new javax.swing.JTextField();
        jpfSenha = new javax.swing.JPasswordField();
        jlAviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlpLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlLogin.setText("Login");

        jlSenha.setText("Senha");

        jbLogar.setText("Logar");
        jbLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLogarActionPerformed(evt);
            }
        });
        jbLogar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLogarKeyPressed(evt);
            }
        });

        jlIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/4635-60843.png"))); // NOI18N

        jtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtLoginKeyPressed(evt);
            }
        });

        jpfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpfSenhaKeyPressed(evt);
            }
        });

        jlpLogin.setLayer(jlLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpLogin.setLayer(jlSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpLogin.setLayer(jbLogar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpLogin.setLayer(jlIcone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpLogin.setLayer(jtLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpLogin.setLayer(jpfSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpLogin.setLayer(jlAviso, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpLoginLayout = new javax.swing.GroupLayout(jlpLogin);
        jlpLogin.setLayout(jlpLoginLayout);
        jlpLoginLayout.setHorizontalGroup(
            jlpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpLoginLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jlpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpLoginLayout.createSequentialGroup()
                        .addGroup(jlpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlLogin)
                            .addComponent(jlSenha))
                        .addGap(30, 30, 30)
                        .addGroup(jlpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jpfSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jtLogin, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jbLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jlIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jlpLoginLayout.setVerticalGroup(
            jlpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpLoginLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpLoginLayout.createSequentialGroup()
                        .addGroup(jlpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlLogin))
                        .addGap(19, 19, 19)
                        .addGroup(jlpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlSenha)
                            .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jbLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpLogin)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpLogin)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logar() {
        try {

            UsuarioServicos us = ServicosFactory.getUsuarioServicos();

            UsuarioVO uVO = new UsuarioVO();

            uVO.setLogin(jtLogin.getText());

            uVO.setSenha(
                    String.valueOf(
                            jpfSenha.getPassword()));

            if (us.validarSenha(uVO)) {
                abrirMenuPrincipal();
                this.setVisible(false);
            } else {
                cont++;

                jlAviso.setText(cont + "ª tentativa! Login/senha inválido(s)!");

                if (cont == 3) {
                    System.exit(EXIT_ON_CLOSE);
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! " + e.getMessage());
        }
    }

    private void abrirMenuPrincipal() {
        Menu mp = new Menu();
        mp.setVisible(true);
    }

    private void jbLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLogarActionPerformed
        logar();
    }//GEN-LAST:event_jbLogarActionPerformed

    private void jtLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jpfSenha.grabFocus();
        }
    }//GEN-LAST:event_jtLoginKeyPressed

    private void jpfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            logar();
        }
    }//GEN-LAST:event_jpfSenhaKeyPressed

    private void jbLogarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLogarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            logar();
        }
    }//GEN-LAST:event_jbLogarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUILogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbLogar;
    private javax.swing.JLabel jlAviso;
    private javax.swing.JLabel jlIcone;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLayeredPane jlpLogin;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtLogin;
    // End of variables declaration//GEN-END:variables
}
